<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>sistemas_inteligentes</groupId>
    <artifactId>upm_helper</artifactId>
    <version>1.0.0-SNAPSHOT</version>

	<properties>
	 	<maven.wagon.http.ssl.insecure>true</maven.wagon.http.ssl.insecure>
	 	<maven.wagon.http.ssl.allowall>true</maven.wagon.http.ssl.allowall>
	    <maven.wagon.http.ssl.ignore.validity.dates>true</maven.wagon.http.ssl.ignore.validity.dates>
	</properties>

    <repositories>
        <repository>
            <id>local-lib</id>
            <url>file://${project.basedir}/lib</url>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
            	<groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>run_indexer</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>1.3.2</version>
                        <configuration>
                            <mainClass>jade.Boot</mainClass>
                            <arguments>
                                <argument>-gui</argument>
                                <argument>agenteIndexador:faqs_practicum.IndexerAgent</argument>
                            </arguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>run_indexer_2</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>1.3.2</version>
                        <configuration>
                            <mainClass>jade.Boot</mainClass>
                            <arguments>
                                <argument>-conf</argument>
                                <argument>src/main/resources/jade.properties</argument>
                            </arguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>com.tilab.jade</groupId>
            <artifactId>jade</artifactId>
            <version>4.5.0</version>
        </dependency>
        
        <dependency>
        	<groupId>org.apache.lucene</groupId>
        	<artifactId>lucene-core</artifactId>
			<version>10.4.0</version>
        </dependency>
        
        <dependency>
        	<groupId>org.apache.lucene</groupId>
        	<artifactId>lucene-analysis-common</artifactId>
			<version>10.4.0</version>	
        </dependency>
        
        <dependency>
        	<groupId>org.json</groupId>
        	<artifactId>json</artifactId>
        	<version>20240303</version>
        </dependency>

        <dependency>
        	<groupId>org.apache.lucene</groupId>
        	<artifactId>lucene-queryparser</artifactId>
        	<version>10.4.0</version>
        </dependency>
    </dependencies>
</project>